export const CategoryTypes = {
    GET_CATEGORY: 'GET_CATEGORY',
    GET_CATEGORY_PENDING: 'GET_CATEGORY_PENDING',
    GET_CATEGORY_FULFILLED: 'GET_CATEGORY_FULFILLED',
    GET_CATEGORY_REJECTED: 'GET_CATEGORY_REJECTED',
}
export const CategoryToday = {
    GET_CATEGORY_TODAY: 'GET_CATEGORY_TODAY',
    GET_CATEGORY_TODAY_PENDING: 'GET_CATEGORY_TODAY_PENDING',
    GET_CATEGORY_TODAY_FULFILLED: 'GET_CATEGORY_TODAY_FULFILLED',
    GET_CATEGORY_TODAY_REJECTED: 'GET_CATEGORY_TODAY_REJECTED',
}
export const PageCategory = {
    GET_PAGE_CATEGORY: 'GET_PAGE_CATEGORY',
    GET_PAGE_CATEGORY_PENDING: 'GET_PAGE_CATEGORY_PENDING',
    GET_PAGE_CATEGORY_FULFILLED: 'GET_PAGE_CATEGORY_FULFILLED',
    GET_PAGE_CATEGORY_REJECTED: 'GET_PAGE_CATEGORY_REJECTED',
}
export const SearchEvent = {
    GET_SEARCH_EVENT: 'GET_SEARCH_EVENT',
    GET_SEARCH_EVENT_PENDING: 'GET_SEARCH_EVENT_PENDING',
    GET_SEARCH_EVENT_FULFILLED: 'GET_SEARCH_EVENT_FULFILLED',
    GET_SEARCH_EVENT_REJECTED: 'GET_SEARCH_EVENT_REJECTED',
}
export const EventDetail = {
    GET_EVENT_DETAIL: 'GET_EVENT_DETAIL',
    GET_EVENT_DETAIL_PENDING: 'GET_EVENT_DETAIL_PENDING',
    GET_EVENT_DETAIL_FULFILLED: 'GET_EVENT_DETAIL_FULFILLED',
    GET_EVENT_DETAIL_REJECTED: 'GET_EVENT_DETAIL_REJECTED',
}
export const ProfileTypes = {
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_PENDING: 'GET_PROFILE_PENDING',
    GET_PROFILE_FULFILLED: 'GET_PROFILE_FULFILLED',
    GET_PROFILE_REJECTED: 'GET_PROFILE_REJECTED',
}
export const STATS_LOGIN = "STATS_LOGIN";
export const STATS_LOGIN_PENDING = "STATS_LOGIN_PENDING";